### PR TITLE
Fix update_mecs_method: rename v0.3 GHG FBS method to ghgi_mecs

### PR DESCRIPTION
**Pull request by MoLi7**
cc:
Closes:

## What changed? Why?

`update_mecs_method` has been broken since #403: `_select_flowsa_ghg_method` returns the FBS method `GHG_national_Cornerstone_2023_release_v0.3`, and flowsa's loader mistakes the `.3` for a version suffix, strips it, so `load_yaml_dict` returns `None` → `AttributeError: 'NoneType' object has no attribute 'pop'` in `generateFlowBySector`. Renaming to a dot-free name fixes the load.

- `bedrock/transform/ghg/GHG_national_Cornerstone_2023_release_v0.3.yaml` → `GHG_national_Cornerstone_2023_ghgi_mecs.yaml`

The new name also describes the method (EPA GHGI 2023 + EIA MECS attribution) and avoids colliding with the unrelated CEDA-based `GHG_national_Cornerstone_2023_mecs.yaml`.

Updates the single consumer (`derived.py:92` return value + docstring) and the comment in `2025_usa_cornerstone_ghg_mecs.yaml`.

## Testing

`ruff`, `black --check`, `mypy` pass. Generated the FBS end-to-end via `getFlowBySector("GHG_national_Cornerstone_2023_ghgi_mecs")` — 7,133 rows, 2023 EPA GHGI; previously crashed at method load.

### CODE REVIEW

**Comment by MoLi7** [comment]
* **#478** <a href="https://app.graphite.com/github/pr/cornerstone-data/bedrock/478?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/cornerstone-data/bedrock/478?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by catherinebirney — APPROVED** [review]
